// Import the Metadata type from Next.js for type safety
import type { Metadata } from "next";
// Import the Geist and Geist_Mono font loaders from Next.js Google Fonts integration
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Load the Geist Sans font with a custom CSS variable and Latin subset
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Load the Geist Mono font with a custom CSS variable and Latin subset
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define site-wide metadata for SEO and browser display
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // Apply the loaded font variables and antialiasing to the body element
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Render the page content */}
        {children}
      </body>
    </html>
  );
}
